print ("Hola Mundo")
print ("hola", "mundo")
print ("Hola", "Mundo", sep="-")
print("hola mundo", "h", "t",sep="-")
print("hola-mundo", )
print ("hola", end=" ")
print("mundo")
print("world")
print("Python", "Java", "C++", "JavaScript", sep= " -> ")